ALGORITMO REEMPLAZAR DATO
1 PEDIR DATO PARA UBICAR
2 RECORRE EL ARRAY Y PREGUNTA POR EL DATO, PARA ENCONTRARLO
3 SI LO ENCUENTRA, MOSTRAR LOS DATOS, SI LO ENCUENTRA PEDIR REINGRESO DE DATO A REEMPLAZAR
3-5 SI NO LO ENCUENTRA , INFORMARLO
